/*
 * Copyright 2025 Haiku, Inc.
 * All rights reserved. Distributed under the terms of the MIT License.
 *
 * RfcommSession — RFCOMM multiplexer session over L2CAP.
 */

#include "RfcommSession.h"

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <sys/socket.h>
#include <sys/time.h>

#include <bluetooth/L2CAP/btL2CAP.h>
#include <l2cap.h>


#define TRACE_RFCOMM(fmt, ...) \
	fprintf(stderr, "RFCOMM: " fmt, ##__VA_ARGS__)


/* =========================================================================
 * CRC-8 table for RFCOMM FCS
 *
 * Polynomial: x^8 + x^2 + x + 1  (reversed form: 0xE0)
 * Generated by shifting each byte through the polynomial bit-by-bit.
 * ========================================================================= */

const uint8 RfcommSession::sFcsTable[256] = {
	0x00, 0x91, 0xE3, 0x72, 0x07, 0x96, 0xE4, 0x75,
	0x0E, 0x9F, 0xED, 0x7C, 0x09, 0x98, 0xEA, 0x7B,
	0x1C, 0x8D, 0xFF, 0x6E, 0x1B, 0x8A, 0xF8, 0x69,
	0x12, 0x83, 0xF1, 0x60, 0x15, 0x84, 0xF6, 0x67,
	0x38, 0xA9, 0xDB, 0x4A, 0x3F, 0xAE, 0xDC, 0x4D,
	0x36, 0xA7, 0xD5, 0x44, 0x31, 0xA0, 0xD2, 0x43,
	0x24, 0xB5, 0xC7, 0x56, 0x23, 0xB2, 0xC0, 0x51,
	0x2A, 0xBB, 0xC9, 0x58, 0x2D, 0xBC, 0xCE, 0x5F,
	0x70, 0xE1, 0x93, 0x02, 0x77, 0xE6, 0x94, 0x05,
	0x7E, 0xEF, 0x9D, 0x0C, 0x79, 0xE8, 0x9A, 0x0B,
	0x6C, 0xFD, 0x8F, 0x1E, 0x6B, 0xFA, 0x88, 0x19,
	0x62, 0xF3, 0x81, 0x10, 0x65, 0xF4, 0x86, 0x17,
	0x48, 0xD9, 0xAB, 0x3A, 0x4F, 0xDE, 0xAC, 0x3D,
	0x46, 0xD7, 0xA5, 0x34, 0x41, 0xD0, 0xA2, 0x33,
	0x54, 0xC5, 0xB7, 0x26, 0x53, 0xC2, 0xB0, 0x21,
	0x5A, 0xCB, 0xB9, 0x28, 0x5D, 0xCC, 0xBE, 0x2F,
	0xE0, 0x71, 0x03, 0x92, 0xE7, 0x76, 0x04, 0x95,
	0xEE, 0x7F, 0x0D, 0x9C, 0xE9, 0x78, 0x0A, 0x9B,
	0xFC, 0x6D, 0x1F, 0x8E, 0xFB, 0x6A, 0x18, 0x89,
	0xF2, 0x63, 0x11, 0x80, 0xF5, 0x64, 0x16, 0x87,
	0xD8, 0x49, 0x3B, 0xAA, 0xDF, 0x4E, 0x3C, 0xAD,
	0xD6, 0x47, 0x35, 0xA4, 0xD1, 0x40, 0x32, 0xA3,
	0xC4, 0x55, 0x27, 0xB6, 0xC3, 0x52, 0x20, 0xB1,
	0xCA, 0x5B, 0x29, 0xB8, 0xCD, 0x5C, 0x2E, 0xBF,
	0x90, 0x01, 0x73, 0xE2, 0x97, 0x06, 0x74, 0xE5,
	0x9E, 0x0F, 0x7D, 0xEC, 0x99, 0x08, 0x7A, 0xEB,
	0x8C, 0x1D, 0x6F, 0xFE, 0x8B, 0x1A, 0x68, 0xF9,
	0x82, 0x13, 0x61, 0xF0, 0x85, 0x14, 0x66, 0xF7,
	0xA8, 0x39, 0x4B, 0xDA, 0xAF, 0x3E, 0x4C, 0xDD,
	0xA6, 0x37, 0x45, 0xD4, 0xA1, 0x30, 0x42, 0xD3,
	0xB4, 0x25, 0x57, 0xC6, 0xB3, 0x22, 0x50, 0xC1,
	0xBA, 0x2B, 0x59, 0xC8, 0xBD, 0x2C, 0x5E, 0xCF
};


/* =========================================================================
 * Constructor / Destructor
 * ========================================================================= */

RfcommSession::RfcommSession()
	:
	fSocket(-1),
	fMuxUp(false),
	fRunning(false),
	fIsInitiator(true),
	fMtu(RFCOMM_DEFAULT_MTU),
	fMuxOpenSem(-1),
	fChannelOpenSem(-1),
	fChannelOpenDlci(0),
	fRecvThread(-1)
{
	for (int i = 0; i < RFCOMM_MAX_DLCIS; i++) {
		fDlcis[i].state = RFCOMM_DLCI_CLOSED;
		fDlcis[i].waitSem = -1;
		fDlcis[i].recvHead = 0;
		fDlcis[i].recvTail = 0;
		fDlcis[i].mtu = RFCOMM_DEFAULT_MTU;
		fDlcis[i].cbfc = false;
		fDlcis[i].localCredits = 0;
		fDlcis[i].remoteCredits = 0;
	}
}


RfcommSession::~RfcommSession()
{
	Disconnect();
}


/* =========================================================================
 * Connection lifecycle
 * ========================================================================= */

status_t
RfcommSession::Connect(const bdaddr_t& remote)
{
	if (fSocket >= 0)
		return B_BUSY;

	/* Create L2CAP socket */
	fSocket = socket(PF_BLUETOOTH, SOCK_STREAM, BLUETOOTH_PROTO_L2CAP);
	if (fSocket < 0) {
		TRACE_RFCOMM("socket() failed: %s\n", strerror(errno));
		return B_ERROR;
	}

	/* Set 10-second receive timeout */
	struct timeval tv;
	tv.tv_sec = 10;
	tv.tv_usec = 0;
	setsockopt(fSocket, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

	/* Connect to remote RFCOMM PSM (0x0003) */
	struct sockaddr_l2cap addr;
	memset(&addr, 0, sizeof(addr));
	addr.l2cap_len = sizeof(addr);
	addr.l2cap_family = PF_BLUETOOTH;
	addr.l2cap_psm = L2CAP_PSM_RFCOMM;
	memcpy(&addr.l2cap_bdaddr, &remote, sizeof(bdaddr_t));

	TRACE_RFCOMM("Connecting L2CAP to PSM 3 (RFCOMM)...\n");
	if (connect(fSocket, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
		TRACE_RFCOMM("connect() failed: %s\n", strerror(errno));
		close(fSocket);
		fSocket = -1;
		return B_ERROR;
	}
	TRACE_RFCOMM("L2CAP connected.\n");

	/* Create mux-open semaphore */
	fMuxOpenSem = create_sem(0, "rfcomm_mux_open");
	if (fMuxOpenSem < 0) {
		close(fSocket);
		fSocket = -1;
		return B_NO_MEMORY;
	}

	/* Spawn receive thread */
	fRunning = true;
	fRecvThread = spawn_thread(_RecvLoopEntry, "rfcomm_recv",
		B_NORMAL_PRIORITY, this);
	if (fRecvThread < 0) {
		delete_sem(fMuxOpenSem);
		fMuxOpenSem = -1;
		close(fSocket);
		fSocket = -1;
		fRunning = false;
		return B_ERROR;
	}
	resume_thread(fRecvThread);

	/* Send SABM on DLCI 0 to open the multiplexer control channel */
	status_t result = _SendSABM(0);
	if (result != B_OK) {
		Disconnect();
		return result;
	}

	/* Wait for UA response (5 seconds) */
	result = acquire_sem_etc(fMuxOpenSem, 1, B_RELATIVE_TIMEOUT, 5000000LL);
	if (result != B_OK) {
		TRACE_RFCOMM("Mux open timed out\n");
		Disconnect();
		return B_TIMED_OUT;
	}

	if (!fMuxUp) {
		TRACE_RFCOMM("Mux rejected (DM received)\n");
		Disconnect();
		return B_ERROR;
	}

	TRACE_RFCOMM("Multiplexer open (DLCI 0 established)\n");
	return B_OK;
}


status_t
RfcommSession::AcceptFrom(int connectedSocket)
{
	if (fSocket >= 0)
		return B_BUSY;

	fSocket = connectedSocket;
	fIsInitiator = false;

	/* Set 10-second receive timeout */
	struct timeval tv;
	tv.tv_sec = 10;
	tv.tv_usec = 0;
	setsockopt(fSocket, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

	/* Create mux-open semaphore */
	fMuxOpenSem = create_sem(0, "rfcomm_mux_open");
	if (fMuxOpenSem < 0) {
		fSocket = -1;
		return B_NO_MEMORY;
	}

	/* Create channel-open notification semaphore */
	fChannelOpenSem = create_sem(0, "rfcomm_chan_open");
	if (fChannelOpenSem < 0) {
		delete_sem(fMuxOpenSem);
		fMuxOpenSem = -1;
		fSocket = -1;
		return B_NO_MEMORY;
	}

	/* Spawn receive thread */
	fRunning = true;
	fRecvThread = spawn_thread(_RecvLoopEntry, "rfcomm_recv",
		B_NORMAL_PRIORITY, this);
	if (fRecvThread < 0) {
		delete_sem(fChannelOpenSem);
		fChannelOpenSem = -1;
		delete_sem(fMuxOpenSem);
		fMuxOpenSem = -1;
		fSocket = -1;
		fRunning = false;
		return B_ERROR;
	}
	resume_thread(fRecvThread);

	TRACE_RFCOMM("Server mode: waiting for remote to open multiplexer...\n");

	/* Wait for remote to send SABM on DLCI 0 (30s) */
	status_t result = acquire_sem_etc(fMuxOpenSem, 1,
		B_RELATIVE_TIMEOUT, 30000000LL);
	if (result != B_OK) {
		TRACE_RFCOMM("Mux open timed out (server mode)\n");
		Disconnect();
		return B_TIMED_OUT;
	}

	if (!fMuxUp) {
		TRACE_RFCOMM("Mux failed (server mode)\n");
		Disconnect();
		return B_ERROR;
	}

	TRACE_RFCOMM("Multiplexer open (server mode, DLCI 0 established)\n");
	return B_OK;
}


uint8
RfcommSession::WaitForChannel(bigtime_t timeout)
{
	if (fChannelOpenSem < 0)
		return 0;

	status_t result = acquire_sem_etc(fChannelOpenSem, 1,
		B_RELATIVE_TIMEOUT, timeout);
	if (result != B_OK)
		return 0;

	return fChannelOpenDlci;
}


void
RfcommSession::Disconnect()
{
	fRunning = false;

	if (fMuxUp && fSocket >= 0)
		_SendDISC(0);

	fMuxUp = false;

	if (fSocket >= 0) {
		close(fSocket);
		fSocket = -1;
	}

	if (fRecvThread >= 0) {
		status_t dummy;
		wait_for_thread(fRecvThread, &dummy);
		fRecvThread = -1;
	}

	if (fMuxOpenSem >= 0) {
		delete_sem(fMuxOpenSem);
		fMuxOpenSem = -1;
	}

	if (fChannelOpenSem >= 0) {
		delete_sem(fChannelOpenSem);
		fChannelOpenSem = -1;
	}

	for (int i = 0; i < RFCOMM_MAX_DLCIS; i++) {
		fDlcis[i].state = RFCOMM_DLCI_CLOSED;
		if (fDlcis[i].waitSem >= 0) {
			delete_sem(fDlcis[i].waitSem);
			fDlcis[i].waitSem = -1;
		}
		fDlcis[i].recvHead = 0;
		fDlcis[i].recvTail = 0;
		fDlcis[i].cbfc = false;
		fDlcis[i].localCredits = 0;
		fDlcis[i].remoteCredits = 0;
	}
}


/* =========================================================================
 * Channel management
 * ========================================================================= */

status_t
RfcommSession::OpenChannel(uint8 serverChannel)
{
	if (!fMuxUp)
		return B_NOT_ALLOWED;

	if (serverChannel < 1 || serverChannel > RFCOMM_MAX_CHANNELS)
		return B_BAD_VALUE;

	/* Compute DLCI: direction=1 (initiator) | (channel << 1) */
	uint8 dlci = RFCOMM_DLCI(1, serverChannel);
	if (dlci >= RFCOMM_MAX_DLCIS)
		return B_BAD_VALUE;

	RfcommDlciInfo& info = fDlcis[dlci];
	if (info.state != RFCOMM_DLCI_CLOSED)
		return B_BUSY;

	/* Create wait semaphore */
	info.waitSem = create_sem(0, "rfcomm_dlci_wait");
	if (info.waitSem < 0)
		return B_NO_MEMORY;

	info.state = RFCOMM_DLCI_OPENING;
	info.recvHead = 0;
	info.recvTail = 0;

	/* Send PN (Parameter Negotiation) */
	status_t result = _SendPN(dlci, RFCOMM_DEFAULT_MTU);
	if (result != B_OK) {
		info.state = RFCOMM_DLCI_CLOSED;
		delete_sem(info.waitSem);
		info.waitSem = -1;
		return result;
	}

	/* Wait for PN response (5s) */
	result = acquire_sem_etc(info.waitSem, 1, B_RELATIVE_TIMEOUT, 5000000LL);
	if (result != B_OK) {
		TRACE_RFCOMM("PN response timed out for DLCI %u\n", dlci);
		info.state = RFCOMM_DLCI_CLOSED;
		delete_sem(info.waitSem);
		info.waitSem = -1;
		return B_TIMED_OUT;
	}

	/* Send SABM to open the DLC */
	result = _SendSABM(dlci);
	if (result != B_OK) {
		info.state = RFCOMM_DLCI_CLOSED;
		delete_sem(info.waitSem);
		info.waitSem = -1;
		return result;
	}

	/* Wait for UA (5s) */
	result = acquire_sem_etc(info.waitSem, 1, B_RELATIVE_TIMEOUT, 5000000LL);
	if (result != B_OK) {
		TRACE_RFCOMM("SABM response timed out for DLCI %u\n", dlci);
		info.state = RFCOMM_DLCI_CLOSED;
		delete_sem(info.waitSem);
		info.waitSem = -1;
		return B_TIMED_OUT;
	}

	if (info.state != RFCOMM_DLCI_OPEN) {
		TRACE_RFCOMM("Channel rejected for DLCI %u\n", dlci);
		delete_sem(info.waitSem);
		info.waitSem = -1;
		return B_ERROR;
	}

	/* Send MSC (Modem Status) — activate DTR, RTS, DSR */
	_SendMSC(dlci, RFCOMM_MSC_DEFAULT);

	/* Grant initial credits to remote so it can send data */
	if (info.cbfc) {
		_GrantCredits(dlci, 7);
	}

	TRACE_RFCOMM("Channel open: DLCI %u (server channel %u), MTU %u%s\n",
		dlci, serverChannel, info.mtu,
		info.cbfc ? " [CBFC]" : "");
	return B_OK;
}


void
RfcommSession::CloseChannel(uint8 dlci)
{
	if (dlci == 0 || dlci >= RFCOMM_MAX_DLCIS)
		return;

	RfcommDlciInfo& info = fDlcis[dlci];
	if (info.state != RFCOMM_DLCI_OPEN)
		return;

	info.state = RFCOMM_DLCI_CLOSING;
	_SendDISC(dlci);

	/* Wait briefly for UA */
	if (info.waitSem >= 0)
		acquire_sem_etc(info.waitSem, 1, B_RELATIVE_TIMEOUT, 2000000LL);

	info.state = RFCOMM_DLCI_CLOSED;
	if (info.waitSem >= 0) {
		delete_sem(info.waitSem);
		info.waitSem = -1;
	}
}


/* =========================================================================
 * Data I/O
 * ========================================================================= */

ssize_t
RfcommSession::Send(uint8 dlci, const void* data, size_t length)
{
	if (dlci == 0 || dlci >= RFCOMM_MAX_DLCIS)
		return B_BAD_VALUE;
	if (fDlcis[dlci].state != RFCOMM_DLCI_OPEN)
		return B_NOT_ALLOWED;

	const uint8* p = (const uint8*)data;
	size_t remaining = length;
	RfcommDlciInfo& info = fDlcis[dlci];
	uint16 maxPayload = info.mtu;

	TRACE_RFCOMM("Send DLCI %u: %zu bytes, localCredits=%ld, "
		"remoteCredits=%ld, mtu=%u\n", dlci, length,
		(long)info.localCredits, (long)info.remoteCredits, maxPayload);

	while (remaining > 0) {
		uint16 chunk = (remaining > maxPayload) ? maxPayload
			: (uint16)remaining;

		status_t result;
		if (info.cbfc) {
			/* In CBFC mode, consume one local credit per frame.
			 * Wait up to 30 seconds for the remote to grant more
			 * credits (60 retries × 500 ms). */
			if (info.localCredits <= 0) {
				TRACE_RFCOMM("No credits to send on DLCI %u, "
					"waiting...\n", dlci);
				int retries = 60;
				while (info.localCredits <= 0 && retries-- > 0)
					snooze(500000);
				if (info.localCredits <= 0) {
					TRACE_RFCOMM("Credit timeout on DLCI %u after "
						"30 s\n", dlci);
					return B_WOULD_BLOCK;
				}
			}
			/* Send regular UIH (P/F=0) for data.
			 * Credits are granted separately via _GrantCredits. */
			result = _SendUIH(dlci, p, chunk);
			if (result == B_OK)
				info.localCredits--;
		} else {
			result = _SendUIH(dlci, p, chunk);
		}

		if (result != B_OK)
			return result;
		p += chunk;
		remaining -= chunk;
	}

	return (ssize_t)length;
}


ssize_t
RfcommSession::Receive(uint8 dlci, void* buffer, size_t maxLength,
	bigtime_t timeout)
{
	if (dlci == 0 || dlci >= RFCOMM_MAX_DLCIS)
		return B_BAD_VALUE;

	RfcommDlciInfo& info = fDlcis[dlci];
	if (info.state != RFCOMM_DLCI_OPEN && info.recvHead == info.recvTail)
		return B_NOT_ALLOWED;

	/* Wait for data if buffer is empty */
	if (info.recvHead == info.recvTail) {
		if (info.waitSem < 0)
			return B_NOT_ALLOWED;

		status_t result = acquire_sem_etc(info.waitSem, 1,
			B_RELATIVE_TIMEOUT, timeout);
		if (result != B_OK)
			return result;
	}

	/* Copy available data from circular buffer */
	uint8* dst = (uint8*)buffer;
	size_t copied = 0;
	while (copied < maxLength && info.recvTail != info.recvHead) {
		dst[copied++] = info.recvBuf[info.recvTail % RFCOMM_RECV_BUF_SIZE];
		info.recvTail++;
	}

	return (ssize_t)copied;
}


/* =========================================================================
 * Frame sending
 * ========================================================================= */

status_t
RfcommSession::_SendFrame(uint8 dlci, uint8 control,
	const uint8* data, uint16 dataLen)
{
	if (fSocket < 0)
		return B_NOT_ALLOWED;

	uint8 buf[5 + dataLen + 1];  /* addr + ctrl + len(1-2) + data + fcs */
	uint8* p = buf;

	/* Address C/R bit (BT Core Spec Vol 3 Part F, Table 5.2):
	 *   Initiator: commands C/R=1, responses C/R=0
	 *   Responder: commands C/R=0, responses C/R=1 */
	uint8 frameType = RFCOMM_FRAME_TYPE(control);
	bool isResponse = (frameType == RFCOMM_UA || frameType == RFCOMM_DM);
	uint8 cr;
	if (fIsInitiator)
		cr = isResponse ? 0 : 1;
	else
		cr = isResponse ? 1 : 0;

	*p++ = RFCOMM_ADDR(cr, dlci);

	/* Control */
	*p++ = control;

	/* Length */
	if (dataLen <= 127) {
		*p++ = RFCOMM_LEN_1BYTE(dataLen);
	} else {
		*p++ = RFCOMM_LEN_2BYTE_LO(dataLen);
		*p++ = RFCOMM_LEN_2BYTE_HI(dataLen);
	}

	/* Data */
	if (data != NULL && dataLen > 0) {
		memcpy(p, data, dataLen);
		p += dataLen;
	}

	/* FCS: for UIH, computed over Address + Control only (2 bytes).
	 * For SABM/UA/DISC/DM, computed over Address + Control + Length. */
	uint8 fcsLen;
	if (frameType == RFCOMM_UIH)
		fcsLen = 2;  /* address + control */
	else
		fcsLen = (uint8)(p - buf - dataLen);  /* address + control + length byte(s) */

	*p++ = _ComputeFCS(buf, fcsLen);

	ssize_t totalLen = p - buf;
	ssize_t sent = send(fSocket, buf, totalLen, 0);
	if (sent != totalLen) {
		TRACE_RFCOMM("send() failed: %s (sent %zd of %zd)\n",
			strerror(errno), sent, totalLen);
		return B_IO_ERROR;
	}

	return B_OK;
}


status_t
RfcommSession::_SendSABM(uint8 dlci)
{
	TRACE_RFCOMM("TX SABM on DLCI %u\n", dlci);
	return _SendFrame(dlci, RFCOMM_SABM_PF, NULL, 0);
}


status_t
RfcommSession::_SendUA(uint8 dlci)
{
	TRACE_RFCOMM("TX UA on DLCI %u\n", dlci);
	return _SendFrame(dlci, RFCOMM_UA_PF, NULL, 0);
}


status_t
RfcommSession::_SendDISC(uint8 dlci)
{
	TRACE_RFCOMM("TX DISC on DLCI %u\n", dlci);
	return _SendFrame(dlci, RFCOMM_DISC_PF, NULL, 0);
}


status_t
RfcommSession::_SendUIH(uint8 dlci, const uint8* data, uint16 dataLen)
{
	return _SendFrame(dlci, RFCOMM_UIH, data, dataLen);
}


status_t
RfcommSession::_SendUIHCredits(uint8 dlci, uint8 credits,
	const uint8* data, uint16 dataLen)
{
	/* UIH frame with P/F=1 and credit byte prepended to data.
	 * The credit byte is the first byte of the information field
	 * when P/F is set in UIH with CBFC. */
	if (fSocket < 0)
		return B_NOT_ALLOWED;

	uint8 buf[6 + dataLen + 1];  /* addr+ctrl+len(2)+credit+data+fcs */
	uint8* p = buf;

	/* Address */
	uint8 cr = fIsInitiator ? 1 : 0;
	*p++ = RFCOMM_ADDR(cr, dlci);

	/* Control: UIH with P/F set */
	*p++ = RFCOMM_UIH | RFCOMM_PF;

	/* Length (data only — credit byte NOT included per TS 07.10) */
	if (dataLen <= 127) {
		*p++ = RFCOMM_LEN_1BYTE(dataLen);
	} else {
		*p++ = RFCOMM_LEN_2BYTE_LO(dataLen);
		*p++ = RFCOMM_LEN_2BYTE_HI(dataLen);
	}

	/* Credit byte */
	*p++ = credits;

	/* Data */
	if (data != NULL && dataLen > 0) {
		memcpy(p, data, dataLen);
		p += dataLen;
	}

	/* FCS: for UIH, computed over Address + Control only */
	*p++ = _ComputeFCS(buf, 2);

	ssize_t totalLen = p - buf;
	ssize_t sent = send(fSocket, buf, totalLen, 0);
	if (sent != totalLen) {
		TRACE_RFCOMM("send() failed: %s (sent %zd of %zd)\n",
			strerror(errno), sent, totalLen);
		return B_IO_ERROR;
	}

	return B_OK;
}


void
RfcommSession::_GrantCredits(uint8 dlci, uint8 credits)
{
	if (dlci >= RFCOMM_MAX_DLCIS || !fDlcis[dlci].cbfc)
		return;

	TRACE_RFCOMM("Granting %u credits to remote for DLCI %u\n",
		credits, dlci);

	/* Send UIH with P/F=1, credit byte, and no data */
	_SendUIHCredits(dlci, credits, NULL, 0);
	fDlcis[dlci].remoteCredits += credits;
}


/* =========================================================================
 * Multiplexer commands (UIH on DLCI 0)
 * ========================================================================= */

status_t
RfcommSession::_SendPN(uint8 dlci, uint16 mtu)
{
	TRACE_RFCOMM("TX PN for DLCI %u, MTU %u\n", dlci, mtu);

	/* Build MCC header + PN params as UIH payload on DLCI 0 */
	uint8 payload[2 + RFCOMM_PN_SIZE];

	/* MCC type byte: PN command (C/R=1, EA=1) */
	payload[0] = RFCOMM_MCC_CMD(RFCOMM_MCC_PN);
	/* MCC length (EA=1) */
	payload[1] = RFCOMM_LEN_1BYTE(RFCOMM_PN_SIZE);

	/* PN parameters */
	rfcomm_pn_params* pn = (rfcomm_pn_params*)(payload + 2);
	pn->dlci = dlci;
	pn->flow_control = 0xF0;  /* request credit-based flow control */
	pn->priority = 0;
	pn->ack_timer = 0;
	pn->mtu = mtu;  /* already little-endian on LE host */
	pn->max_retrans = 0;
	pn->credits = 7;  /* initial credits for remote to send */

	return _SendUIH(0, payload, sizeof(payload));
}


status_t
RfcommSession::_SendMSC(uint8 dlci, uint8 signals)
{
	TRACE_RFCOMM("TX MSC for DLCI %u, signals 0x%02X\n", dlci, signals);

	uint8 payload[2 + 2];  /* MCC header + MSC params (2 bytes) */

	/* MCC type byte: MSC command */
	payload[0] = RFCOMM_MCC_CMD(RFCOMM_MCC_MSC);
	/* MCC length */
	payload[1] = RFCOMM_LEN_1BYTE(2);

	/* MSC parameters */
	payload[2] = RFCOMM_ADDR(1, dlci);  /* DLCI address byte (CR=1, EA=1) */
	payload[3] = signals | 0x01;  /* V.24 signals + EA bit */

	return _SendUIH(0, payload, sizeof(payload));
}


/* =========================================================================
 * FCS computation
 * ========================================================================= */

uint8
RfcommSession::_ComputeFCS(const uint8* data, uint8 len)
{
	uint8 fcs = 0xFF;
	for (uint8 i = 0; i < len; i++)
		fcs = sFcsTable[fcs ^ data[i]];
	return 0xFF - fcs;
}


bool
RfcommSession::_CheckFCS(const uint8* data, uint8 len, uint8 fcs)
{
	uint8 check = 0xFF;
	for (uint8 i = 0; i < len; i++)
		check = sFcsTable[check ^ data[i]];
	check = sFcsTable[check ^ fcs];
	return check == RFCOMM_FCS_CHECK;
}


/* =========================================================================
 * Receive thread
 * ========================================================================= */

status_t
RfcommSession::_RecvLoopEntry(void* arg)
{
	((RfcommSession*)arg)->_RecvLoop();
	return B_OK;
}


void
RfcommSession::_RecvLoop()
{
	uint8 buf[2048];

	while (fRunning && fSocket >= 0) {
		ssize_t received = recv(fSocket, buf, sizeof(buf), 0);
		if (received <= 0) {
			if (errno == EAGAIN || errno == EWOULDBLOCK)
				continue;
			if (fRunning)
				TRACE_RFCOMM("recv() error: %s\n", strerror(errno));
			break;
		}

		TRACE_RFCOMM("RX raw %zd bytes:", received);
		for (ssize_t i = 0; i < received && i < 48; i++)
			fprintf(stderr, " %02X", buf[i]);
		if (received > 48)
			fprintf(stderr, "...");
		fprintf(stderr, "\n");

		/* Parse all RFCOMM frames in this L2CAP PDU */
		ssize_t offset = 0;
		while (offset < received) {
			ssize_t consumed = _ParseFrame(buf + offset,
				received - offset);
			if (consumed <= 0)
				break;
			offset += consumed;
		}
	}

	/* Signal all waiting threads that we're done */
	if (fMuxOpenSem >= 0)
		release_sem(fMuxOpenSem);
	if (fChannelOpenSem >= 0)
		release_sem(fChannelOpenSem);

	for (int i = 0; i < RFCOMM_MAX_DLCIS; i++) {
		if (fDlcis[i].waitSem >= 0)
			release_sem(fDlcis[i].waitSem);
	}
}


ssize_t
RfcommSession::_ParseFrame(const uint8* buf, ssize_t len)
{
	if (len < 4) {
		TRACE_RFCOMM("RX frame too short (%zd bytes)\n", len);
		return -1;
	}

	/* Parse address byte */
	uint8 addrByte = buf[0];
	uint8 dlci = RFCOMM_GET_DLCI(addrByte);
	/* uint8 cr = RFCOMM_GET_CR(addrByte); */

	/* Parse control byte */
	uint8 control = buf[1];
	uint8 frameType = RFCOMM_FRAME_TYPE(control);

	/* Parse length */
	uint16 dataLen;
	uint8 headerLen;
	if (RFCOMM_LEN_EA(buf[2])) {
		/* Single-byte length */
		dataLen = RFCOMM_GET_LEN1(buf[2]);
		headerLen = 3;
	} else {
		/* Two-byte length */
		if (len < 5) {
			TRACE_RFCOMM("RX frame too short for 2-byte length\n");
			return -1;
		}
		dataLen = RFCOMM_GET_LEN1(buf[2]) | ((uint16)buf[3] << 7);
		headerLen = 4;
	}

	/* When CBFC is active and P/F=1 in UIH, some implementations
	 * (Android/Fluoride, per original TS 07.10 5.4.6.3.7) place
	 * the credit byte OUTSIDE the length field.  Detect this by
	 * trying FCS at both positions. */
	uint16 infoLen = dataLen;

	if (frameType == RFCOMM_UIH && (control & RFCOMM_PF) != 0
		&& dlci < RFCOMM_MAX_DLCIS && fDlcis[dlci].cbfc) {
		/* Standard position: FCS at headerLen + dataLen */
		bool stdOk = ((ssize_t)(headerLen + dataLen + 1) <= len)
			&& _CheckFCS(buf, 2, buf[headerLen + dataLen]);
		/* Alternative position: credit not in length, FCS at +1 */
		bool altOk = ((ssize_t)(headerLen + dataLen + 2) <= len)
			&& _CheckFCS(buf, 2, buf[headerLen + dataLen + 1]);

		if (!stdOk && altOk) {
			infoLen = dataLen + 1;
			TRACE_RFCOMM("CBFC credit byte not in length "
				"(len=%u, actual info=%u)\n", dataLen, infoLen);
		}
	}

	if ((ssize_t)(headerLen + infoLen + 1) > len) {
		TRACE_RFCOMM("RX frame truncated (headerLen=%u, infoLen=%u, "
			"total=%zd)\n", headerLen, infoLen, len);
		return -1;
	}

	const uint8* data = buf + headerLen;
	uint8 fcs = buf[headerLen + infoLen];

	/* Verify FCS */
	uint8 fcsLen;
	if (frameType == RFCOMM_UIH)
		fcsLen = 2;
	else
		fcsLen = headerLen;

	if (!_CheckFCS(buf, fcsLen, fcs)) {
		TRACE_RFCOMM("RX FCS fail DLCI %u: fcsLen=%u, fcs@[%u]=0x%02X, "
			"expected over {0x%02X", dlci, fcsLen,
			headerLen + infoLen, fcs, buf[0]);
		for (uint8 fi = 1; fi < fcsLen; fi++)
			fprintf(stderr, ",0x%02X", buf[fi]);
		fprintf(stderr, "}\n");
		return -1;
	}

	ssize_t frameSize = headerLen + infoLen + 1;

	/* Dispatch by frame type */
	switch (frameType) {
		case RFCOMM_UA:
			TRACE_RFCOMM("RX UA on DLCI %u\n", dlci);
			if (dlci == 0) {
				fMuxUp = true;
				if (fMuxOpenSem >= 0)
					release_sem(fMuxOpenSem);
			} else if (dlci < RFCOMM_MAX_DLCIS) {
				RfcommDlciInfo& info = fDlcis[dlci];
				if (info.state == RFCOMM_DLCI_OPENING) {
					info.state = RFCOMM_DLCI_OPEN;
					if (info.waitSem >= 0)
						release_sem(info.waitSem);
				} else if (info.state == RFCOMM_DLCI_CLOSING) {
					info.state = RFCOMM_DLCI_CLOSED;
					if (info.waitSem >= 0)
						release_sem(info.waitSem);
				}
			}
			break;

		case RFCOMM_DM:
			TRACE_RFCOMM("RX DM on DLCI %u\n", dlci);
			if (dlci == 0) {
				fMuxUp = false;
				if (fMuxOpenSem >= 0)
					release_sem(fMuxOpenSem);
			} else if (dlci < RFCOMM_MAX_DLCIS) {
				fDlcis[dlci].state = RFCOMM_DLCI_CLOSED;
				if (fDlcis[dlci].waitSem >= 0)
					release_sem(fDlcis[dlci].waitSem);
			}
			break;

		case RFCOMM_DISC:
			TRACE_RFCOMM("RX DISC on DLCI %u\n", dlci);
			_SendUA(dlci);
			if (dlci == 0) {
				fMuxUp = false;
			} else if (dlci < RFCOMM_MAX_DLCIS) {
				fDlcis[dlci].state = RFCOMM_DLCI_CLOSED;
				if (fDlcis[dlci].waitSem >= 0)
					release_sem(fDlcis[dlci].waitSem);
			}
			break;

		case RFCOMM_SABM:
			TRACE_RFCOMM("RX SABM on DLCI %u (incoming)\n", dlci);
			/* Accept incoming connections — respond with UA */
			_SendUA(dlci);
			if (dlci == 0) {
				fMuxUp = true;
				if (fMuxOpenSem >= 0)
					release_sem(fMuxOpenSem);
			} else if (dlci < RFCOMM_MAX_DLCIS) {
				RfcommDlciInfo& info = fDlcis[dlci];
				info.state = RFCOMM_DLCI_OPEN;
				info.recvHead = 0;
				info.recvTail = 0;
				if (info.waitSem < 0)
					info.waitSem = create_sem(0, "rfcomm_dlci_wait");
				/* Notify server that a channel was opened */
				fChannelOpenDlci = dlci;
				if (fChannelOpenSem >= 0)
					release_sem(fChannelOpenSem);
			}
			break;

		case RFCOMM_UIH:
		{
			const uint8* payload = data;
			uint16 payloadLen = infoLen;
			bool hasPF = (control & RFCOMM_PF) != 0;

			if (dlci == 0) {
				/* Multiplexer control command */
				_HandleMuxCommand(payload, payloadLen);
			} else if (dlci < RFCOMM_MAX_DLCIS) {
				RfcommDlciInfo& info = fDlcis[dlci];

				/* Handle credit byte in CBFC mode */
				if (hasPF && info.cbfc && payloadLen > 0) {
					uint8 credits = payload[0];
					info.localCredits += credits;
					TRACE_RFCOMM("RX %u credits for DLCI %u "
						"(total=%ld)\n", credits, dlci,
						(long)info.localCredits);
					payload++;
					payloadLen--;
				}

				/* Enqueue data (may be 0 if credit-only frame) */
				if (payloadLen > 0)
					_EnqueueData(dlci, payload, payloadLen);

				/* Grant more credits when remote is running low */
				if (info.cbfc) {
					info.remoteCredits--;
					if (info.remoteCredits <= 2)
						_GrantCredits(dlci, 7);
				}
			}
			break;
		}

		default:
			TRACE_RFCOMM("RX unknown frame type 0x%02X on DLCI %u\n",
				frameType, dlci);
			break;
	}

	return frameSize;
}


void
RfcommSession::_HandleMuxCommand(const uint8* data, uint16 len)
{
	if (len < 2)
		return;

	uint8 typeByte = data[0];
	uint8 mccType = RFCOMM_MCC_TYPE(typeByte);
	bool isCommand = RFCOMM_MCC_IS_CMD(typeByte);

	/* Parse MCC length */
	uint8 mccLen;
	const uint8* mccData;
	if (RFCOMM_LEN_EA(data[1])) {
		mccLen = RFCOMM_GET_LEN1(data[1]);
		mccData = data + 2;
	} else {
		if (len < 3)
			return;
		mccLen = RFCOMM_GET_LEN1(data[1]) | (data[2] << 7);
		mccData = data + 3;
	}

	switch (mccType) {
		case RFCOMM_MCC_PN:
		{
			if (mccLen < RFCOMM_PN_SIZE)
				break;

			const rfcomm_pn_params* pn = (const rfcomm_pn_params*)mccData;
			uint8 dlci = pn->dlci;
			uint16 remoteMtu = pn->mtu;

			TRACE_RFCOMM("RX PN %s for DLCI %u, MTU %u, "
				"flow=0x%02X, credits=%u\n",
				isCommand ? "cmd" : "rsp", dlci, remoteMtu,
				pn->flow_control, pn->credits);

			if (isCommand) {
				/* Remote is requesting PN — respond with our params */
				uint8 resp[2 + RFCOMM_PN_SIZE];
				resp[0] = RFCOMM_MCC_RSP(RFCOMM_MCC_PN);
				resp[1] = RFCOMM_LEN_1BYTE(RFCOMM_PN_SIZE);

				rfcomm_pn_params* rpn = (rfcomm_pn_params*)(resp + 2);
				rpn->dlci = dlci;
				rpn->flow_control = 0x00;
				rpn->priority = pn->priority;
				rpn->ack_timer = 0;
				rpn->mtu = (remoteMtu < RFCOMM_DEFAULT_MTU) ? remoteMtu
					: RFCOMM_DEFAULT_MTU;
				rpn->max_retrans = 0;
				rpn->credits = 0;

				_SendUIH(0, resp, sizeof(resp));
			} else {
				/* Response to our PN request */
				if (dlci < RFCOMM_MAX_DLCIS) {
					RfcommDlciInfo& info = fDlcis[dlci];
					info.mtu = (remoteMtu < RFCOMM_DEFAULT_MTU) ? remoteMtu
						: RFCOMM_DEFAULT_MTU;
					fMtu = info.mtu;
					/* Check if remote accepted CBFC */
					if (pn->flow_control == 0xE0) {
						info.cbfc = true;
						info.localCredits = pn->credits;
						TRACE_RFCOMM("CBFC active for DLCI %u, "
							"local credits=%u\n",
							dlci, pn->credits);
					}
					if (info.waitSem >= 0)
						release_sem(info.waitSem);
				}
			}
			break;
		}

		case RFCOMM_MCC_MSC:
		{
			if (mccLen < 2)
				break;

			uint8 dlci = RFCOMM_GET_DLCI(mccData[0]);
			uint8 signals = mccData[1];

			TRACE_RFCOMM("RX MSC %s for DLCI %u, signals 0x%02X\n",
				isCommand ? "cmd" : "rsp", dlci, signals);

			if (isCommand) {
				/* Respond with MSC response */
				uint8 resp[4];
				resp[0] = RFCOMM_MCC_RSP(RFCOMM_MCC_MSC);
				resp[1] = RFCOMM_LEN_1BYTE(2);
				resp[2] = mccData[0];  /* echo DLCI addr */
				resp[3] = signals;     /* echo signals */
				_SendUIH(0, resp, sizeof(resp));
			}
			break;
		}

		default:
			TRACE_RFCOMM("RX unknown MCC type 0x%02X (%s)\n",
				mccType, isCommand ? "cmd" : "rsp");
			if (isCommand) {
				/* Respond with NSC (Non-Supported Command) */
				uint8 resp[3];
				resp[0] = RFCOMM_MCC_RSP(RFCOMM_MCC_NSC);
				resp[1] = RFCOMM_LEN_1BYTE(1);
				resp[2] = typeByte;
				_SendUIH(0, resp, sizeof(resp));
			}
			break;
	}
}


/* =========================================================================
 * Buffer helpers
 * ========================================================================= */

void
RfcommSession::_EnqueueData(uint8 dlci, const uint8* data, uint16 len)
{
	if (dlci >= RFCOMM_MAX_DLCIS)
		return;

	RfcommDlciInfo& info = fDlcis[dlci];

	for (uint16 i = 0; i < len; i++) {
		uint32 nextHead = info.recvHead + 1;
		/* Drop bytes if buffer full (shouldn't happen with flow control) */
		if ((nextHead - info.recvTail) > RFCOMM_RECV_BUF_SIZE)
			break;
		info.recvBuf[info.recvHead % RFCOMM_RECV_BUF_SIZE] = data[i];
		info.recvHead = nextHead;
	}

	/* Signal waiting reader */
	if (info.waitSem >= 0)
		release_sem(info.waitSem);
}
